/*
 * File: app/view/AddShopMenu.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TeShopifyExt.view.AddShopMenu', {
    extend: 'Ext.menu.Menu',
    alias: 'widget.addshopmenu',

    width: 180,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'menuitem',
                    text: 'Edit Shopify Shop',
                    listeners: {
                        click: {
                            fn: me.onMenuitemClick1,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'menuseparator'
                },
                {
                    xtype: 'menuitem',
                    text: 'Add Shopify Shop',
                    listeners: {
                        click: {
                            fn: me.onMenuitemClick11,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onMenuitemClick1: function(item, e, eOpts) {
        var tree = Ext.getCmp('ShopifyShopsTree');
        if (tree.getSelectionModel().hasSelection()){
            var selectedNode = tree.getSelectionModel().getSelection()[0];
            var win = Ext.widget('shopifyshopwindow');
            win.show();
            win.down('form').loadRecord(selectedNode);
        }
    },

    onMenuitemClick11: function(item, e, eOpts) {
        var win = Ext.widget('shopifyshopwindow');
        win.show();
    }

});