/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TeShopifyExt.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'TeShopifyExt.view.NavBarLeft',
        'TeShopifyExt.view.ShopifyShopsTree'
    ],

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'north',
                    border: false,
                    height: 40,
                    id: 'northPanel',
                    ui: 'header',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    html: '<h2>TeShopify</h2>',
                                    margin: '0 0 0 50'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1
                        },
                        {
                            xtype: 'container',
                            flex: 1
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    border: false,
                    id: 'centralPanel',
                    layout: {
                        type: 'fit'
                    },
                    bodyBorder: false
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    id: 'westPanel',
                    width: 220,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    collapsed: false,
                    collapsible: false,
                    items: [
                        {
                            xtype: 'navbarleft',
                            border: false,
                            margin: '20 0 0 0',
                            bodyBorder: false
                        },
                        {
                            xtype: 'container',
                            height: 35,
                            margin: '100 0 0 0',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    margin: '10 0 0 20',
                                    boxLabel: 'Show Shopify Shops',
                                    listeners: {
                                        change: {
                                            fn: me.onCheckboxfieldChange,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'shopifyshopstree'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onCheckboxfieldChange: function(field, newValue, oldValue, eOpts) {
        if (newValue === true) {
            Ext.getCmp('ShopifyShopsTree').show();
        } else {
            Ext.getCmp('ShopifyShopsTree').hide();
        }
    }

});