/*
 * File: app/view/NavBarLeft.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TeShopifyExt.view.NavBarLeft', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.navbarleft',

    border: false,
    margin: '0 0 0 20',
    hideCollapseTool: true,
    hideHeaders: true,
    store: 'MainTreeStore',
    folderSort: false,
    lines: false,
    useArrows: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            root: {
                name: 'Shopify Shops',
                expanded: true
            },
            viewConfig: {
                border: false
            },
            columns: [
                {
                    xtype: 'treecolumn',
                    dataIndex: 'name',
                    text: 'MyTreeColumn',
                    flex: 1
                }
            ],
            listeners: {
                itemcontextmenu: {
                    fn: me.onTreepanelItemContextMenu,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onTreepanelItemContextMenu: function(dataview, record, item, index, e, eOpts) {
        console.log(record);
    }

});