/*
 * File: app/view/ProductWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TeShopifyExt.view.ProductWindow', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.productwindow',

    requires: [
        'TeShopifyExt.view.ProductForm'
    ],

    autoScroll: true,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    bodyBorder: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    style: 'borderBottom: 1px solid #ededed; backgroundColor: #fafafa;',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            height: 52,
                            style: 'borderBottom: 1px solid #ededed; backgroundColor: #fafafa;',
                            items: [
                                {
                                    xtype: 'button',
                                    margin: '0 0 0 20',
                                    iconCls: 'tags',
                                    scale: 'medium',
                                    text: 'Products',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick2,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    id: 'ProductButton',
                                    margin: '0 0 0 5',
                                    scale: 'large',
                                    text: 'New Product'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    scale: 'medium',
                                    text: 'Cancel',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 20 0 0',
                                    scale: 'medium',
                                    text: 'Save',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick1,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'productform',
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick2: function(button, e, eOpts) {
        var main = Ext.getCmp('centralPanel');
        main.removeAll();
        var panel = Ext.widget('productsview');
        main.add(panel);
    },

    onButtonClick: function(button, e, eOpts) {
        var main = Ext.getCmp('centralPanel');
        main.removeAll();
        var panel = Ext.widget('productsview');
        main.add(panel);
    },

    onButtonClick1: function(button, e, eOpts) {
        var panel = Ext.getCmp('ProductForm');
        var form = panel.getForm();
        if (form.isValid()) {
            panel.setLoading('Saving ... ');
            var id = panel.down('hiddenfield[name="id"]').getValue();
            var url = '';                    
            if ( id > 0) {
                url = '/shopify/product/update';
            } else {
                url = '/shopify/product/create';
            } 
            form.submit({
                url: url,
                success: function(form,action){
                    panel.setLoading(false);
                    Ext.StoreMgr.lookup('ProductStore').reload();

                },
                failure: function(form, action){
                    panel.setLoading(false);
                    var msg  = action.result.msg; 
                    Ext.Msg.show({
                        msg: msg,
                        buttons: Ext.Msg.OK,
                        icon: Ext.Msg.WARNING
                    });
                    button.up('window').close();
                }
            });
        }   
    }

});