/*
 * File: app/view/ProductWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TeShopifyExt.view.ProductWindow', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.productwindow',

    margin: '0 20 0 10',
    autoScroll: true,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    bodyBorder: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'container',
                            width: 200,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    width: 30
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            html: '<a href="#"><h2>Products</h2></a>'
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            height: 50,
                            items: [
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    scale: 'medium',
                                    text: 'Cancel',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    scale: 'medium',
                                    text: 'Save'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'form',
                    layout: {
                        type: 'auto'
                    },
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    width: 300,
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            width: 40
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: {
                                                align: 'stretch',
                                                type: 'vbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    html: '<h3>Product Details</h3>'
                                                },
                                                {
                                                    xtype: 'container',
                                                    html: '<span>Write a name and description, and provide a type and vendor to categorize this product.</span>'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            width: 40
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: {
                                        align: 'stretch',
                                        type: 'vbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            margin: '20 0 0 0',
                                            fieldLabel: 'Product Name',
                                            labelAlign: 'top',
                                            labelSeparator: ' ',
                                            emptyText: 'eg. Unicorn crest short sleeve tree'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            flex: 1,
                                            margin: '10 0 0 0 ',
                                            fieldLabel: 'Description',
                                            labelAlign: 'top',
                                            labelSeparator: ' '
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    margin: '0 20 0 0',
                                                    fieldLabel: 'Product Type',
                                                    labelAlign: 'top',
                                                    labelSeparator: ' '
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    fieldLabel: 'Vendor',
                                                    labelAlign: 'top',
                                                    labelSeparator: ' '
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    width: 300,
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            width: 40
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: {
                                                align: 'stretch',
                                                type: 'vbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    html: '<h3>Inventory & variants</h3>'
                                                },
                                                {
                                                    xtype: 'container',
                                                    html: '<span>Manage inventory, and configure the options for selling this product.</span>'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            width: 40
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    items: [
                                        {
                                            xtype: 'container',
                                            margin: '10 0 0 0',
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    margin: '0 20 0 0',
                                                    fieldLabel: 'Price',
                                                    labelAlign: 'top',
                                                    labelSeparator: ' '
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    fieldLabel: 'Compare at price',
                                                    labelAlign: 'top',
                                                    labelSeparator: ' '
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            margin: '10 0 0 0',
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    margin: '0 20 0 0',
                                                    fieldLabel: 'SKU',
                                                    labelAlign: 'top',
                                                    labelSeparator: ' '
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    fieldLabel: 'Barcode',
                                                    labelAlign: 'top',
                                                    labelSeparator: ' '
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            margin: '10 0 0 0',
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    boxLabel: 'Charge taxes',
                                                    checked: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            margin: '10 0 0 0',
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    boxLabel: 'Require a shipping address'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var main = Ext.getCmp('centralPanel');
        main.removeAll();
        var panel = Ext.widget('productsview');
        main.add(panel);
    }

});