/*
 * File: app/view/ProductOptionWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TeShopifyExt.view.ProductOptionWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.productoptionwindow',

    height: 250,
    width: 400,
    layout: {
        type: 'fit'
    },
    title: 'Add A New Option',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: false,
                    id: 'ProductOptionForm',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Internal Name',
                            labelSeparator: '',
                            name: 'code'
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Public Name',
                            labelSeparator: '',
                            name: 'name'
                        },
                        {
                            xtype: 'textareafield',
                            fieldLabel: 'Values',
                            labelSeparator: '',
                            name: 'values'
                        },
                        {
                            xtype: 'hiddenfield',
                            flex: 1,
                            fieldLabel: 'Label',
                            name: 'id',
                            value: 0
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            text: 'Add',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        var panel = Ext.getCmp('ProductOptionForm');
        var form = panel.getForm();
        if (form.isValid()) {
            panel.setLoading('Saving ... ');
            var id = panel.down('hiddenfield[name="id"]').getValue();
            var url = '';                    
            if ( id > 0) {
                url = '/shopify/option/edit';
            } else {
                url = '/shopify/option/add';
            } 
            form.submit({
                url: url,
                success: function(form,action){
                    panel.setLoading(false);
                    Ext.StoreMgr.lookup('ProductOptionStore').reload();
                    button.up('window').close();
                },
                failure: function(form, action){
                    panel.setLoading(false);
                    var msg  = action.result.msg; 
                    Ext.Msg.show({
                        msg: msg,
                        buttons: Ext.Msg.OK,
                        icon: Ext.Msg.WARNING
                    });
                    button.up('window').close();
                }
            });
        }   
    }

});