/*
 * File: app/view/SelectShopify.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TeShopifyExt.view.SelectShopify', {
    extend: 'Ext.window.Window',
    alias: 'widget.selectshopify',

    height: 350,
    id: 'SelectShopify',
    width: 600,
    layout: {
        type: 'fit'
    },
    title: 'Select Shopify Shop',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'SelectShopifyGrid',
                    store: 'WebserviceStore',
                    selModel: Ext.create('Ext.selection.CheckboxModel', {
                        mode: 'SINGLE',
                        listeners: {
                            select: {
                                fn: me.onCheckboxModelSelect,
                                scope: me
                            }
                        }
                    }),
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            dataIndex: 'name',
                            text: 'Shopify Shop'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'uri',
                            text: 'Shopify Shop Url',
                            flex: 1
                        }
                    ],
                    listeners: {
                        render: {
                            fn: me.onGridpanelRender,
                            scope: me
                        }
                    },
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            ui: 'footer',
                            items: [
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 20',
                                    text: 'Load Products',
                                    listeners: {
                                        click: {
                                            fn: me.onButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onCheckboxModelSelect: function(rowmodel, record, index, eOpts) {

    },

    onGridpanelRender: function(component, eOpts) {
        component.getStore().load();
    },

    onButtonClick: function(button, e, eOpts) {
        var sel = button.up('gridpanel').getSelectionModel().getSelection();
        var id = sel[0].get('id');
        button.up('window').close();
        var main = Ext.getCmp('centralPanel');
        main.removeAll();
        var panel = Ext.widget('onlineproductsview');
        main.add(panel);
        panel. down('button[text="Shopify"]').setText(sel[0].get('name'));
        Ext.StoreMgr.lookup('OnlineProductStore').load({
            params: { id: id}
        });

    }

});