/*
 * File: app/model/VariantModel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TeShopifyExt.model.VariantModel', {
    extend: 'Ext.data.Model',

    uses: [
        'TeShopifyExt.model.ProductModel'
    ],

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'product_id',
            type: 'int'
        },
        {
            name: 'title',
            type: 'auto'
        },
        {
            name: 'fulfillment_service',
            type: 'auto'
        },
        {
            name: 'grams',
            type: 'int'
        },
        {
            name: 'inventory_management',
            type: 'string'
        },
        {
            name: 'inventory_policy',
            type: 'string'
        },
        {
            name: 'inventory_quantity',
            type: 'int'
        },
        {
            name: 'metafield',
            type: 'auto'
        },
        {
            name: 'position',
            type: 'auto'
        },
        {
            name: 'price',
            type: 'float'
        },
        {
            name: 'requires_shipping',
            type: 'string'
        },
        {
            name: 'sku',
            type: 'string'
        },
        {
            name: 'taxable',
            type: 'auto'
        }
    ],

    belongsTo: {
        model: 'TeShopifyExt.model.ProductModel'
    }
});