/*
 * File: app/model/WebserviceModel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TeShopifyExt.model.WebserviceModel', {
    extend: 'Ext.data.Model',
    alias: 'model.webservicesmodel',

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'name',
            type: 'string'
        },
        {
            name: 'description',
            type: 'auto'
        },
        {
            name: 'uri',
            type: 'auto'
        },
        {
            name: 'apikey',
            type: 'auto'
        },
        {
            name: 'sharedsecret',
            type: 'auto'
        },
        {
            name: 'password',
            type: 'auto'
        },
        {
            dateFormat: 'Y-m-d H:i:s',
            name: 'syncdate',
            type: 'date'
        },
        {
            convert: function(v, rec) {
                return rec.get('syncdate');
            },
            name: 'synctime'
        },
        {
            name: 'ordersync',
            type: 'int'
        },
        {
            name: 'ordersync_lastid'
        }
    ]
});